### ISSUE TITLE
Support for mockery 0.9.x

### ISSUE THREAD

**Issue by ahoffmann-wi** [php-mock/php-mock-mockery#1]
This package has a requirement of `mockery/mockery` with version `^0.8`. Can this be updated to use the latest version of mockery?

**Comment by malkusch** [comment]
As soon as travis will be green I'll release version 0.3 which will depend on mockery-0.9.

Mockery-0.9 introduced [a new feature](https://github.com/padraic/mockery/issues/268) which broke my tests. So the only change was working around that new feature in a test.
