### ISSUE TITLE
php-mock/php-mock 2.1 compatibility

### ISSUE THREAD

**Issue by udavka** [php-mock/php-mock-mockery#10]
This library is not compatible with a latest php-mock/php-mock.

**Comment by webimpress** [comment]
@udavka Can you provide more informations?

I have just run the build:
https://travis-ci.org/php-mock/php-mock-mockery/builds/505663299
and so far so good. What is not compatible? What errors are you getting?

**Comment by udavka** [comment]
Sorry, the problem is actually not in this library, but in php-mock/php-mock.
It contains "archive": { "exclude": ["/tests"] } in composer.json and under certain conditions this directory may be not loaded in the /vendor/php-mock/php-mock.

php-mock contains in this /tests directory some files that are referenced from /autoload.php. And due to this everything may fail.

**Comment by webimpress** [comment]
@udavka Can you open then issue in php-mock if you think there is an issue? Please provide an example, so I can replicate it and fix. Thanks!
