### ISSUE TITLE
Cannot install because only php-mock 1.x is supported

### ISSUE THREAD

**Issue by iquito** [php-mock/php-mock-mockery#8]
php-mock-mockery only supports php-mock 1.x, so after installing php-mock 2.0 the following errors occur in composer:

    Problem 1
    - php-mock/php-mock-integration 1.0.0 requires php-mock/php-mock ^1 -> satisfiable by php-mock/php-mock[1.0.0, 1.0.1] but these conflict with your requirements or minimum-stability.
    - php-mock/php-mock-mockery 1.2.0 requires php-mock/php-mock-integration ^1 -> satisfiable by php-mock/php-mock-integration[1.0.0].
    - Installation request for php-mock/php-mock-mockery ^1.2 -> satisfiable by php-mock/php-mock-mockery[1.2.0].

I suspect this is probably just an oversight in composer.json, or is there a specific reason why php-mock-mockery would not work with php-mock 2.0? I posted the issue here although the problematic package is actually php-mock-integration, but I suspect nobody installs that package specifically.

**Comment by malkusch** [comment]
I didn't upgrade this package to php-mock-2. The changes are minimal and effectively you won't see them when using this API. If you are using php-mock-mockery you shouldn't explicitely require php-mock. Is there a reason why you want php-mock-2?

**Comment by iquito** [comment]
Not specifically, I just happened to install php-mock first and I thought it might be an oversight / too restrictive versioning. If I just require php-mock-mockery the installation works. I do have another issue after that, but I will open a new issue for that.

**Comment by iquito** [comment]
Ah the other issue had a different reason. Thanks for the help and the great library!
